#服务配置
server:
  port: 8082

spring:
#  持久层
  datasource:
    url: jdbc:mysql://120.79.42.11:3306/transocket?useUnicode=true&characterEncoding=utf-8
    username: teavamc
    password: Qwer1234!@#$
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

mybatis:
#  实体类
  type-aliases-package: com.teavamc.transsocket.domain
#  mapper文件扫描位置
  mapper-locations: classpath:mapper/*.xml

#  页面
thymeleaf:
  cache: false
  prefix: classpath:/templates/
  suffix: .html
  mode: HTML5
  encoding: UTF-8

#分页器
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
  returnPageInfo: check

logging:
  config: classpath:log4j2.xml

